language: php

sudo: required

services:
  - docker

cache:
    directories:
        - vendor
        - node_modules

env:
  - TEST_SUITE=unit

php:
    - "5.6"

sudo: false

matrix:
  fast_finish: true

before_install:
    # Start Xvfb in a desktop screen size,
    # otherwise some tests will fail because the links
    # are hidden when Selenium tries to find them.
    ##- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1600x1200x16"
    #- "export DISPLAY=:99.0"
    #- "sh -e /etc/init.d/xvfb start"
    # Ensure node version is up to date
    - nvm install node
    - mkdir -p project project/libraries

install:
    # Install composer modules
    - composer install
    - phpenv rehash
before_script:
    - phpenv config-rm xdebug.ini
script:
    - npm run tests:integration
