language: php

sudo: required

services:
  - docker

cache:
    directories:
        - vendor

env:
  - TEST_SUITE=lint-javascript
  - TEST_SUITE=lint-php
  - TEST_SUITE=unit
  - TEST_SUITE=integration

before_install:
    # Ensure node version is up to date
    - nvm install node
    - npm install
script:
    - npm run tests:$TEST_SUITE
